[package]
name = "transient_db"
version = "0.1.0"
edition = "2024"

[lib]

[[bin]]
name = "transient"

[dependencies]
bincode = { version = "2.0.1", features = ["serde", "derive"] }
serde = { version = "1.0.219", features = ["derive"] }
sled = "0.34.7"
